// Autogenerated types using https://github.com/shakyShane/json-ts
export default interface CDNTweet {
    __typename: string;
    lang: string;
    favorite_count: number;
    possibly_sensitive?: boolean;
    created_at: string;
    display_text_range?: number[];
    entities?: IEntities;
    id_str: string;
    text: string;
    user: IUser;
    edit_control: IEdit_control;
    mediaDetails?: IMediaDetailsItem[];
    photos?: IPhotosItem[];
    conversation_count: number;
    news_action_type: string;
    isEdited: boolean;
    isStaleEdit: boolean;
    place?: IPlace;
    quoted_tweet?: IQuoted_tweet;
    in_reply_to_screen_name?: string;
    in_reply_to_status_id_str?: string;
    in_reply_to_user_id_str?: string;
    self_thread?: ISelf_thread;
    parent?: IParent;
    video?: IVideo;
    covid19_hub_url?: string;
    card?: ICard;
    conversation_control?: IConversation_control;
}
interface IEntities {
    hashtags: IHashtagsItem[];
    urls: IUrlsItem[];
    user_mentions: IUserMentionsItem[];
    symbols: ISymbolsItem[];
    media?: IMediaItem[];
}
interface IUrlsItem {
    display_url: string;
    expanded_url: string;
    indices: number[];
    url: string;
}
interface IMediaItem {
    display_url: string;
    expanded_url: string;
    indices: number[];
    url: string;
}
interface IUser {
    id_str: string;
    name: string;
    profile_image_url_https: string;
    screen_name: string;
    verified: boolean;
    is_blue_verified: boolean;
    verified_type?: string;
    highlighted_label?: IHighlighted_label;
}
interface IEdit_control {
    edit_tweet_ids: string[];
    editable_until_msecs: string;
    is_edit_eligible: boolean;
    edits_remaining: string;
}
interface IMediaDetailsItem {
    display_url: string;
    expanded_url: string;
    ext_media_availability: IExt_media_availability;
    indices: number[];
    media_url_https: string;
    original_info: IOriginal_info;
    sizes: ISizes;
    type: string;
    url: string;
    additional_media_info?: IAdditional_media_info;
    ext_media_stats?: IExt_media_stats;
    video_info?: IVideo_info;
    ext_alt_text?: string;
}
interface IExt_media_availability {
    status: string;
    reason?: string;
}
interface IOriginal_info {
    height: number;
    width: number;
    focus_rects?: IFocusRectsItem[];
}
interface IFocusRectsItem {
    x: number;
    y: number;
    w: number;
    h: number;
}
interface ISizes {
    large: ILarge;
    medium: IMedium;
    small: ISmall;
    thumb: IThumb;
}
interface ILarge {
    h: number;
    resize: string;
    w: number;
}
interface IMedium {
    h: number;
    resize: string;
    w: number;
}
interface ISmall {
    h: number;
    resize: string;
    w: number;
}
interface IThumb {
    h: number;
    resize: string;
    w: number;
}
interface IPhotosItem {
    backgroundColor: IBackgroundColor;
    cropCandidates: ICropCandidatesItem[];
    expandedUrl: string;
    url: string;
    width: number;
    height: number;
    accessibilityLabel?: string;
}
interface IBackgroundColor {
    red: number;
    green: number;
    blue: number;
}
interface ICropCandidatesItem {
    x: number;
    y: number;
    w: number;
    h: number;
}
interface IPlace {
    full_name: string;
    id: string;
}
interface IQuoted_tweet {
    in_reply_to_screen_name?: string;
    in_reply_to_status_id_str?: string;
    in_reply_to_user_id_str?: string;
    lang: string;
    place?: IPlace;
    reply_count: number;
    retweet_count: number;
    favorite_count: number;
    created_at: string;
    display_text_range: number[];
    entities: IEntities;
    id_str: string;
    text: string;
    user: IUser;
    edit_control?: IEdit_control;
    isEdited?: boolean;
    isStaleEdit?: boolean;
    possibly_sensitive?: boolean;
    mediaDetails?: IMediaDetailsItem[];
    photos?: IPhotosItem[];
    self_thread?: ISelf_thread;
    video?: IVideo;
    conversation_control?: IConversation_control;
}
interface IUserMentionsItem {
    id_str: string;
    indices: number[];
    name: string;
    screen_name: string;
}
interface ISelf_thread {
    id_str: string;
}
interface IHashtagsItem {
    indices: number[];
    text: string;
}
interface IParent {
    lang: string;
    reply_count: number;
    retweet_count: number;
    favorite_count: number;
    self_thread?: ISelf_thread;
    possibly_sensitive?: boolean;
    created_at: string;
    display_text_range: number[];
    entities: IEntities;
    id_str: string;
    text: string;
    user: IUser;
    edit_control: IEdit_control;
    mediaDetails?: IMediaDetailsItem[];
    photos?: IPhotosItem[];
    isEdited: boolean;
    isStaleEdit: boolean;
    in_reply_to_screen_name?: string;
    in_reply_to_status_id_str?: string;
    in_reply_to_user_id_str?: string;
    place?: IPlace;
    video?: IVideo;
    conversation_control?: IConversation_control;
    quoted_tweet?: IQuoted_tweet;
    card?: ICard;
}
interface IAdditional_media_info {
    description?: string;
    embeddable?: boolean;
    title?: string;
}
interface IExt_media_stats {
    view_count: number;
}
interface IVideo_info {
    aspect_ratio: number[];
    duration_millis?: number;
    variants: IVariantsItem[];
}
interface IVariantsItem {
    bitrate?: number;
    content_type?: string;
    url?: string;
    type?: string;
    src?: string;
}
interface IVideo {
    aspectRatio: number[];
    contentType?: string;
    durationMs?: number;
    mediaAvailability?: IMediaAvailability;
    poster: string;
    variants?: IVariantsItem[];
    videoId?: IVideoId;
    viewCount?: number;
}
interface IMediaAvailability {
    status: string;
    reason?: string;
}
interface IVideoId {
    type: string;
    id: string;
}
interface ICard {
    card_platform: ICard_platform;
    name: string;
    url: string;
    binding_values: IBinding_values;
}
interface ICard_platform {
    platform: IPlatform;
}
interface IPlatform {
    audience: IAudience;
    device: IDevice;
}
interface IAudience {
    name: string;
}
interface IDevice {
    name: string;
    version: string;
}
interface IBinding_values {
    description?: IDescription;
    domain?: IDomain;
    creator?: ICreator;
    photo_image_full_size_alt_text?: IPhoto_image_full_size_alt_text;
    vanity_url?: IVanity_url;
    summary_photo_image_alt_text?: ISummary_photo_image_alt_text;
    title?: ITitle;
    card_url: ICard_url;
    photo_image_full_size_large?: IPhoto_image_full_size_large;
    thumbnail_image?: IThumbnail_image;
    thumbnail_image_large?: IThumbnail_image_large;
    summary_photo_image_small?: ISummary_photo_image_small;
    thumbnail_image_original?: IThumbnail_image_original;
    site?: ISite;
    photo_image_full_size_small?: IPhoto_image_full_size_small;
    summary_photo_image_large?: ISummary_photo_image_large;
    thumbnail_image_small?: IThumbnail_image_small;
    thumbnail_image_x_large?: IThumbnail_image_x_large;
    photo_image_full_size_original?: IPhoto_image_full_size_original;
    photo_image_full_size?: IPhoto_image_full_size;
    thumbnail_image_color?: IThumbnail_image_color;
    summary_photo_image_color?: ISummary_photo_image_color;
    summary_photo_image_x_large?: ISummary_photo_image_x_large;
    summary_photo_image?: ISummary_photo_image;
    photo_image_full_size_color?: IPhoto_image_full_size_color;
    photo_image_full_size_x_large?: IPhoto_image_full_size_x_large;
    summary_photo_image_original?: ISummary_photo_image_original;
    player_url?: IPlayer_url;
    player_image_large?: IPlayer_image_large;
    player_image?: IPlayer_image;
    app_star_rating?: IApp_star_rating;
    player_width?: IPlayer_width;
    app_is_free?: IApp_is_free;
    player_image_original?: IPlayer_image_original;
    app_num_ratings?: IApp_num_ratings;
    app_price_amount?: IApp_price_amount;
    player_height?: IPlayer_height;
    app_name?: IApp_name;
    player_image_small?: IPlayer_image_small;
    app_price_currency?: IApp_price_currency;
    player_image_color?: IPlayer_image_color;
    player_image_x_large?: IPlayer_image_x_large;
    website_shortened_url?: IWebsite_shortened_url;
    promo_image?: IPromo_image;
    _forward_card_height_?: I_forward_card_height_;
    promo_image_color?: IPromo_image_color;
    promo_image_original?: IPromo_image_original;
    promo_image_large?: IPromo_image_large;
    promo_image_small?: IPromo_image_small;
    website_dest_url?: IWebsite_dest_url;
    promo_image_x_large?: IPromo_image_x_large;
    website_url?: IWebsite_url;
    app_country?: IApp_country;
    choice1_label?: IChoice1_label;
    choice2_label?: IChoice2_label;
    end_datetime_utc?: IEnd_datetime_utc;
    counts_are_final?: ICounts_are_final;
    choice2_count?: IChoice2_count;
    choice1_count?: IChoice1_count;
    last_updated_datetime_utc?: ILast_updated_datetime_utc;
    duration_minutes?: IDuration_minutes;
    choice3_count?: IChoice3_count;
    choice3_label?: IChoice3_label;
    api?: IApi;
    thumbnail_image_alt_text?: IThumbnail_image_alt_text;
    choice4_label?: IChoice4_label;
    choice4_count?: IChoice4_count;
    tile_image_small?: ITile_image_small;
    tile_image_color?: ITile_image_color;
    tile_image?: ITile_image;
    tile_image_original?: ITile_image_original;
    tile_image_x_large?: ITile_image_x_large;
    tile_image_large?: ITile_image_large;
    cover_promo_image_small?: ICover_promo_image_small;
    thank_you_text?: IThank_you_text;
    cover_promo_image_x_large?: ICover_promo_image_x_large;
    cover_promo_image_color?: ICover_promo_image_color;
    cover_promo_image_large?: ICover_promo_image_large;
    card_id?: ICard_id;
    cover_promo_image_original?: ICover_promo_image_original;
    cta_one_tweet?: ICta_one_tweet;
    cta_one?: ICta_one;
    cover_promo_image?: ICover_promo_image;
    is_360?: IIs_360;
    available_for_replay?: IAvailable_for_replay;
    broadcast_width?: IBroadcast_width;
    googleplay_icon_small?: IGoogleplay_icon_small;
    full_size_thumbnail_url?: IFull_size_thumbnail_url;
    googleplay_icon_large?: IGoogleplay_icon_large;
    url?: IUrl;
    broadcast_state?: IBroadcast_state;
    broadcaster_id?: IBroadcaster_id;
    googleplay_icon_x_large?: IGoogleplay_icon_x_large;
    featured?: IFeatured;
    broadcast_source?: IBroadcast_source;
    app_id_googleplay?: IApp_id_googleplay;
    app_id_iphone?: IApp_id_iphone;
    total_participants?: ITotal_participants;
    apple_icon?: IApple_icon;
    apple_icon_x_large?: IApple_icon_x_large;
    id?: IId;
    broadcaster_twitter_id?: IBroadcaster_twitter_id;
    broadcast_height?: IBroadcast_height;
    initial_camera_orientation?: IInitial_camera_orientation;
    status?: IStatus;
    broadcaster_username?: IBroadcaster_username;
    broadcast_media_key?: IBroadcast_media_key;
    broadcaster_display_name?: IBroadcaster_display_name;
    _omit_link_?: I_omit_link_;
    googleplay_icon?: IGoogleplay_icon;
    apple_icon_large?: IApple_icon_large;
    apple_icon_small?: IApple_icon_small;
    broadcast_invitees_twitter?: IBroadcast_invitees_twitter;
    is_high_latency?: IIs_high_latency;
    amp_url?: IAmp_url;
    cdn_amp_url?: ICdn_amp_url;
    event_thumbnail_color?: IEvent_thumbnail_color;
    event_category?: IEvent_category;
    author?: IAuthor;
    event_thumbnail_original?: IEvent_thumbnail_original;
    event_thumbnail_media_size_crops_16x9_x?: IEvent_thumbnail_media_size_crops_16x9_x;
    square_thumbnail?: ISquare_thumbnail;
    square_thumbnail_color?: ISquare_thumbnail_color;
    square_thumbnail_original?: ISquare_thumbnail_original;
    event_thumbnail_x_large?: IEvent_thumbnail_x_large;
    event_title?: IEvent_title;
    event_thumbnail_media_size_crops_16x9_y?: IEvent_thumbnail_media_size_crops_16x9_y;
    remind_me_toggle_visible?: IRemind_me_toggle_visible;
    event_timeline_id?: IEvent_timeline_id;
    event_subtitle?: IEvent_subtitle;
    event_thumbnail_media_size_crops_16x9_h?: IEvent_thumbnail_media_size_crops_16x9_h;
    square_thumbnail_x_large?: ISquare_thumbnail_x_large;
    event_thumbnail_small?: IEvent_thumbnail_small;
    event_thumbnail_media_size_crops_16x9_w?: IEvent_thumbnail_media_size_crops_16x9_w;
    square_thumbnail_small?: ISquare_thumbnail_small;
    media_type?: IMedia_type;
    event_id?: IEvent_id;
    square_thumbnail_large?: ISquare_thumbnail_large;
    event_thumbnail_large?: IEvent_thumbnail_large;
    event_thumbnail?: IEvent_thumbnail;
    content_duration_seconds?: IContent_duration_seconds;
    player_content_id?: IPlayer_content_id;
    player_owner_id?: IPlayer_owner_id;
    player_hls_url?: IPlayer_hls_url;
    player_stream_url?: IPlayer_stream_url;
    cta_three?: ICta_three;
    cta_two_tweet?: ICta_two_tweet;
    cta_three_tweet?: ICta_three_tweet;
    cta_two?: ICta_two;
    thank_you_vanity_url?: IThank_you_vanity_url;
    player_stream_content_type?: IPlayer_stream_content_type;
    thank_you_url?: IThank_you_url;
    thank_you_shortened_url?: IThank_you_shortened_url;
}
interface IDescription {
    string_value: string;
    type: string;
}
interface IDomain {
    string_value: string;
    type: string;
}
interface ICreator {
    type: string;
    user_value: IUser_value;
}
interface IUser_value {
    id_str: string;
    path: any[];
}
interface IPhoto_image_full_size_alt_text {
    string_value: string;
    type: string;
}
interface IVanity_url {
    scribe_key?: string;
    string_value: string;
    type: string;
}
interface ISummary_photo_image_alt_text {
    string_value: string;
    type: string;
}
interface ITitle {
    string_value: string;
    type: string;
}
interface ICard_url {
    scribe_key: string;
    string_value: string;
    type: string;
}
interface IPhoto_image_full_size_large {
    image_value: IImage_value;
    type: string;
}
interface IImage_value {
    height: number;
    width: number;
    url: string;
    alt?: string;
}
interface IThumbnail_image {
    image_value: IImage_value;
    type: string;
}
interface IThumbnail_image_large {
    image_value: IImage_value;
    type: string;
}
interface ISummary_photo_image_small {
    image_value: IImage_value;
    type: string;
}
interface IThumbnail_image_original {
    image_value: IImage_value;
    type: string;
}
interface ISite {
    scribe_key: string;
    type: string;
    user_value: IUser_value;
}
interface IPhoto_image_full_size_small {
    image_value: IImage_value;
    type: string;
}
interface ISummary_photo_image_large {
    image_value: IImage_value;
    type: string;
}
interface IThumbnail_image_small {
    image_value: IImage_value;
    type: string;
}
interface IThumbnail_image_x_large {
    image_value: IImage_value;
    type: string;
}
interface IPhoto_image_full_size_original {
    image_value: IImage_value;
    type: string;
}
interface IPhoto_image_full_size {
    image_value: IImage_value;
    type: string;
}
interface IThumbnail_image_color {
    image_color_value: IImage_color_value;
    type: string;
}
interface IImage_color_value {
    palette: IPaletteItem[];
}
interface IPaletteItem {
    rgb: IRgb;
    percentage: number;
}
interface IRgb {
    blue: number;
    green: number;
    red: number;
}
interface ISummary_photo_image_color {
    image_color_value: IImage_color_value;
    type: string;
}
interface ISummary_photo_image_x_large {
    image_value: IImage_value;
    type: string;
}
interface ISummary_photo_image {
    image_value: IImage_value;
    type: string;
}
interface IPhoto_image_full_size_color {
    image_color_value: IImage_color_value;
    type: string;
}
interface IPhoto_image_full_size_x_large {
    image_value: IImage_value;
    type: string;
}
interface ISummary_photo_image_original {
    image_value: IImage_value;
    type: string;
}
interface IHighlighted_label {
    description: string;
    badge: IBadge;
    url?: IUrl;
    user_label_type?: string;
    user_label_display_type?: string;
}
interface IBadge {
    url: string;
}
interface IUrl {
    url: string;
    url_type: string;
    string_value?: string;
    type?: string;
}
interface IPlayer_url {
    string_value: string;
    type: string;
}
interface IPlayer_image_large {
    image_value: IImage_value;
    type: string;
}
interface IPlayer_image {
    image_value: IImage_value;
    type: string;
}
interface IApp_star_rating {
    string_value: string;
    type: string;
}
interface IPlayer_width {
    string_value: string;
    type: string;
}
interface IApp_is_free {
    string_value: string;
    type: string;
}
interface IPlayer_image_original {
    image_value: IImage_value;
    type: string;
}
interface IApp_num_ratings {
    string_value: string;
    type: string;
}
interface IApp_price_amount {
    string_value: string;
    type: string;
}
interface IPlayer_height {
    string_value: string;
    type: string;
}
interface IApp_name {
    string_value: string;
    type: string;
}
interface IPlayer_image_small {
    image_value: IImage_value;
    type: string;
}
interface IApp_price_currency {
    string_value: string;
    type: string;
}
interface IPlayer_image_color {
    image_color_value: IImage_color_value;
    type: string;
}
interface IPlayer_image_x_large {
    image_value: IImage_value;
    type: string;
}
interface IConversation_control {
    policy: string;
}
interface IWebsite_shortened_url {
    string_value: string;
    type: string;
}
interface IPromo_image {
    image_value: IImage_value;
    type: string;
}
interface I_forward_card_height_ {
    string_value: string;
    type: string;
}
interface IPromo_image_color {
    image_color_value: IImage_color_value;
    type: string;
}
interface IPromo_image_original {
    image_value: IImage_value;
    type: string;
}
interface IPromo_image_large {
    image_value: IImage_value;
    type: string;
}
interface IPromo_image_small {
    image_value: IImage_value;
    type: string;
}
interface IWebsite_dest_url {
    string_value: string;
    type: string;
}
interface IPromo_image_x_large {
    image_value: IImage_value;
    type: string;
}
interface IWebsite_url {
    string_value: string;
    type: string;
}
interface IApp_country {
    string_value: string;
    type: string;
}
interface IChoice1_label {
    string_value: string;
    type: string;
}
interface IChoice2_label {
    string_value: string;
    type: string;
}
interface IEnd_datetime_utc {
    string_value: string;
    type: string;
}
interface ICounts_are_final {
    boolean_value: boolean;
    type: string;
}
interface IChoice2_count {
    string_value: string;
    type: string;
}
interface IChoice1_count {
    string_value: string;
    type: string;
}
interface ILast_updated_datetime_utc {
    string_value: string;
    type: string;
}
interface IDuration_minutes {
    string_value: string;
    type: string;
}
interface IChoice3_count {
    string_value: string;
    type: string;
}
interface IChoice3_label {
    string_value: string;
    type: string;
}
interface IApi {
    string_value: string;
    type: string;
}
interface IThumbnail_image_alt_text {
    string_value: string;
    type: string;
}
interface IChoice4_label {
    string_value: string;
    type: string;
}
interface IChoice4_count {
    string_value: string;
    type: string;
}
interface ISymbolsItem {
    indices: number[];
    text: string;
}
interface ITile_image_small {
    image_value: IImage_value;
    type: string;
}
interface ITile_image_color {
    image_color_value: IImage_color_value;
    type: string;
}
interface ITile_image {
    image_value: IImage_value;
    type: string;
}
interface ITile_image_original {
    image_value: IImage_value;
    type: string;
}
interface ITile_image_x_large {
    image_value: IImage_value;
    type: string;
}
interface ITile_image_large {
    image_value: IImage_value;
    type: string;
}
interface ICover_promo_image_small {
    image_value: IImage_value;
    type: string;
}
interface IThank_you_text {
    string_value: string;
    type: string;
}
interface ICover_promo_image_x_large {
    image_value: IImage_value;
    type: string;
}
interface ICover_promo_image_color {
    image_color_value: IImage_color_value;
    type: string;
}
interface ICover_promo_image_large {
    image_value: IImage_value;
    type: string;
}
interface ICard_id {
    string_value: string;
    type: string;
}
interface ICover_promo_image_original {
    image_value: IImage_value;
    type: string;
}
interface ICta_one_tweet {
    string_value: string;
    type: string;
}
interface ICta_one {
    string_value: string;
    type: string;
}
interface ICover_promo_image {
    image_value: IImage_value;
    type: string;
}
interface IIs_360 {
    boolean_value: boolean;
    type: string;
}
interface IAvailable_for_replay {
    boolean_value: boolean;
    type: string;
}
interface IBroadcast_width {
    string_value: string;
    type: string;
}
interface IGoogleplay_icon_small {
    image_value: IImage_value;
    type: string;
}
interface IFull_size_thumbnail_url {
    string_value: string;
    type: string;
}
interface IGoogleplay_icon_large {
    image_value: IImage_value;
    type: string;
}
interface IBroadcast_state {
    string_value: string;
    type: string;
}
interface IBroadcaster_id {
    string_value: string;
    type: string;
}
interface IGoogleplay_icon_x_large {
    image_value: IImage_value;
    type: string;
}
interface IFeatured {
    boolean_value: boolean;
    type: string;
}
interface IBroadcast_source {
    string_value: string;
    type: string;
}
interface IApp_id_googleplay {
    string_value: string;
    type: string;
}
interface IApp_id_iphone {
    string_value: string;
    type: string;
}
interface ITotal_participants {
    string_value: string;
    type: string;
}
interface IApple_icon {
    image_value: IImage_value;
    type: string;
}
interface IApple_icon_x_large {
    image_value: IImage_value;
    type: string;
}
interface IId {
    string_value: string;
    type: string;
}
interface IBroadcaster_twitter_id {
    string_value: string;
    type: string;
}
interface IBroadcast_height {
    string_value: string;
    type: string;
}
interface IInitial_camera_orientation {
    string_value: string;
    type: string;
}
interface IStatus {
    string_value: string;
    type: string;
}
interface IBroadcaster_username {
    string_value: string;
    type: string;
}
interface IBroadcast_media_key {
    string_value: string;
    type: string;
}
interface IBroadcaster_display_name {
    string_value: string;
    type: string;
}
interface I_omit_link_ {
    boolean_value: boolean;
    type: string;
}
interface IGoogleplay_icon {
    image_value: IImage_value;
    type: string;
}
interface IApple_icon_large {
    image_value: IImage_value;
    type: string;
}
interface IApple_icon_small {
    image_value: IImage_value;
    type: string;
}
interface IBroadcast_invitees_twitter {
    string_value: string;
    type: string;
}
interface IIs_high_latency {
    boolean_value: boolean;
    type: string;
}
interface IAmp_url {
    string_value: string;
    type: string;
}
interface ICdn_amp_url {
    string_value: string;
    type: string;
}
interface IEvent_thumbnail_color {
    image_color_value: IImage_color_value;
    type: string;
}
interface IEvent_category {
    string_value: string;
    type: string;
}
interface IAuthor {
    type: string;
    user_value: IUser_value;
}
interface IEvent_thumbnail_original {
    image_value: IImage_value;
    type: string;
}
interface IEvent_thumbnail_media_size_crops_16x9_x {
    string_value: string;
    type: string;
}
interface ISquare_thumbnail {
    image_value: IImage_value;
    type: string;
}
interface ISquare_thumbnail_color {
    image_color_value: IImage_color_value;
    type: string;
}
interface ISquare_thumbnail_original {
    image_value: IImage_value;
    type: string;
}
interface IEvent_thumbnail_x_large {
    image_value: IImage_value;
    type: string;
}
interface IEvent_title {
    string_value: string;
    type: string;
}
interface IEvent_thumbnail_media_size_crops_16x9_y {
    string_value: string;
    type: string;
}
interface IRemind_me_toggle_visible {
    boolean_value: boolean;
    type: string;
}
interface IEvent_timeline_id {
    string_value: string;
    type: string;
}
interface IEvent_subtitle {
    string_value: string;
    type: string;
}
interface IEvent_thumbnail_media_size_crops_16x9_h {
    string_value: string;
    type: string;
}
interface ISquare_thumbnail_x_large {
    image_value: IImage_value;
    type: string;
}
interface IEvent_thumbnail_small {
    image_value: IImage_value;
    type: string;
}
interface IEvent_thumbnail_media_size_crops_16x9_w {
    string_value: string;
    type: string;
}
interface ISquare_thumbnail_small {
    image_value: IImage_value;
    type: string;
}
interface IMedia_type {
    string_value: string;
    type: string;
}
interface IEvent_id {
    string_value: string;
    type: string;
}
interface ISquare_thumbnail_large {
    image_value: IImage_value;
    type: string;
}
interface IEvent_thumbnail_large {
    image_value: IImage_value;
    type: string;
}
interface IEvent_thumbnail {
    image_value: IImage_value;
    type: string;
}
interface IContent_duration_seconds {
    string_value: string;
    type: string;
}
interface IPlayer_content_id {
    string_value: string;
    type: string;
}
interface IPlayer_owner_id {
    string_value: string;
    type: string;
}
interface IPlayer_hls_url {
    string_value: string;
    type: string;
}
interface IPlayer_stream_url {
    string_value: string;
    type: string;
}
interface ICta_three {
    string_value: string;
    type: string;
}
interface ICta_two_tweet {
    string_value: string;
    type: string;
}
interface ICta_three_tweet {
    string_value: string;
    type: string;
}
interface ICta_two {
    string_value: string;
    type: string;
}
interface IThank_you_vanity_url {
    string_value: string;
    type: string;
}
interface IPlayer_stream_content_type {
    string_value: string;
    type: string;
}
interface IThank_you_url {
    string_value: string;
    type: string;
}
interface IThank_you_shortened_url {
    string_value: string;
    type: string;
}

